version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
